package fixdol.mekanismelements.common.datagen.providers;

import java.util.concurrent.CompletableFuture;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraft.core.HolderLookup;
import fixdol.mekanismelements.common.datagen.providers.MSBlockTagsProvider;
import fixdol.mekanismelements.common.registries.MSBlocks;
import fixdol.mekanismelements.common.MekanismElements;
import net.minecraft.data.PackOutput;

import net.minecraft.tags.BlockTags;
import net.minecraftforge.common.data.BlockTagsProvider;


public class MSBlockTagsProvider extends BlockTagsProvider {

    public MSBlockTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, MekanismElements.MODID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(MSBlocks.ADSORPTION_SEPARATOR.getBlock())
                .add(MSBlocks.AIR_COMPRESSOR.getBlock())
                .add(MSBlocks.RADIATION_IRRADIATOR.getBlock())
                .add(MSBlocks.CHEMICAL_DEMOLITION_MACHINE.getBlock())
                .add(MSBlocks.SEAWATER_PUMP.getBlock())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE_SLABS.getBlock());
     
        tag(BlockTags.NEEDS_IRON_TOOL)
                .add(MSBlocks.ADSORPTION_SEPARATOR.getBlock())
                .add(MSBlocks.AIR_COMPRESSOR.getBlock())
                .add(MSBlocks.RADIATION_IRRADIATOR.getBlock())
                .add(MSBlocks.CHEMICAL_DEMOLITION_MACHINE.getBlock())
                .add(MSBlocks.SEAWATER_PUMP.getBlock())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE.getBlock())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE_STAIRS.getBlock())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE_SLABS.getBlock())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE_SLABS.getBlock());


        tag(BlockTags.NEEDS_DIAMOND_TOOL)
                .add(MSBlocks.ADSORPTION_SEPARATOR.getBlock())
                .add(MSBlocks.AIR_COMPRESSOR.getBlock())
                .add(MSBlocks.RADIATION_IRRADIATOR.getBlock())
                .add(MSBlocks.SEAWATER_PUMP.getBlock())
                .add(MSBlocks.CHEMICAL_DEMOLITION_MACHINE.getBlock());
    }
}