package com.fxd927.mekanismelements.common.datagen.providers;

import com.fxd927.mekanismelements.common.MekanismElements;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;


public class LanguageGenerator extends LanguageProvider {

    public LanguageGenerator(PackOutput packOutput) {
        super(packOutput, MekanismElements.MODID, "en_us");
    }

    @Override
    protected void addTranslations() {
        add("constants.mekanismelements.mod_name", "Mekanism: Elements");
        add("advancements.mekanismelements.californium.title", "The Reach of Science");
        add("advancements.mekanismelements.californium.description", "Refine Californium, the element with the highest atomic number that has practical applications");
        add("advancements.mekanismelements.neutron_source.title", "Why Did You Think This Was Safe?");
        add("advancements.mekanismelements.neutron_source.description", "Make Neutron Source Pellet from Americium and Beryllium, and hold");
        add("advancements.mekanismelements.radiation_irradiator.title", "Mini-Reactor");
        add("advancements.mekanismelements.radiation_irradiator.description", "Craft a Radiation Irradiator");
        add("advancements.mekanismelements.seawater_pump.title", "I Sea What You Did There");
        add("advancements.mekanismelements.seawater_pump.description", "Craft a Seawater Pump");
        add("block.mekanismelements.adsorption_separator", "Adsorption Separator");
        add("block.mekanismelements.air_compressor", "Air Compressor");
        add("block.mekanismelements.chemical_demolition_machine", "Chemical Demolition Machine");
        add("block.mekanismelements.organic_liquid_extractor", "Organic Liquid Extractor");
        add("block.mekanismelements.radiation_irradiator", "Radiation Irradiator");
        add("block.mekanismelements.radiation_shielding_concrete", "Radiation Shielding Concrete");
        add("block.mekanismelements.seawater_pump", "Seawater Pump");
        add("block.mekanismelements.ammonia", "Liquid Ammonia");
        add("block.mekanismelements.ammonium_nitrate", "Liquid Ammonium Nitrate");
        add("block.mekanismelements.aqua_regia", "Liquid Aqua Regia");
        add("block.mekanismelements.beryllium", "Liquid Beryllium");
        add("block.mekanismelements.bromine", "Liquid Bromine");
        add("block.mekanismelements.compressed_air", "Liquid Compressed Air");
        add("block.mekanismelements.helium", "Liquid Helium");
        add("block.mekanismelements.iodine", "Liquid Iodine");
        add("block.mekanismelements.netherite_acid", "Liquid Netherite Acid");
        add("block.mekanismelements.nitric_acid", "Liquid Nitric Acid");
        add("block.mekanismelements.nitric_oxide", "Liquid Nitric Oxide");
        add("block.mekanismelements.nitrogen", "Liquid Nitrogen");
        add("block.mekanismelements.nitrogen_dioxide", "Liquid Nitrogen Dioxide");
        add("block.mekanismelements.potassium_chloride", "Liquid Potassium Chloride");
        add("block.mekanismelements.potassium_hydroxide", "Liquid Potassium Hydroxide");
        add("block.mekanismelements.potassium_iodide", "Liquid Potassium Iodide");
        add("block.mekanismelements.seawater", "Seawater");
        add("block.mekanismelements.strontium", "Liquid Strontium");
        add("block.mekanismelements.superheated_helium", "Liquid Superheated Helium");
        add("block.mekanismelements.xenon", "Liquid Xenon");
        add("block.mekanismelements.yttrium", "Liquid Yttrium");
        add("block.mekanismelements.aqua_high_quality_concrete", "Aqua High-Quality Concrete");
        add("block.mekanismelements.black_high_quality_concrete", "Black High-Quality Concrete");
        add("block.mekanismelements.blue_high_quality_concrete", "Blue High-Quality Concrete");
        add("block.mekanismelements.brown_high_quality_concrete", "Brown High-Quality Concrete");
        add("block.mekanismelements.cyan_high_quality_concrete", "Cyan High-Quality Concrete");
        add("block.mekanismelements.dark_red_high_quality_concrete", "Dark Red High-Quality Concrete");
        add("block.mekanismelements.gray_high_quality_concrete", "Gray High-Quality Concrete");
        add("block.mekanismelements.green_high_quality_concrete", "Green High-Quality Concrete");
        add("block.mekanismelements.high_quality_concrete", "High-Quality Concrete");
        add("block.mekanismelements.light_blue_high_quality_concrete", "Light Blue High-Quality Concrete");
        add("block.mekanismelements.light_gray_high_quality_concrete", "Light Gray High-Quality Concrete");
        add("block.mekanismelements.lime_high_quality_concrete", "Lime High-Quality Concrete");
        add("block.mekanismelements.magenta_high_quality_concrete", "Magenta High-Quality Concrete");
        add("block.mekanismelements.orange_high_quality_concrete", "Orange High-Quality Concrete");
        add("block.mekanismelements.pink_high_quality_concrete", "Pink High-Quality Concrete");
        add("block.mekanismelements.purple_high_quality_concrete", "Purple High-Quality Concrete");
        add("block.mekanismelements.red_high_quality_concrete", "Red High-Quality Concrete");
        add("block.mekanismelements.white_high_quality_concrete", "White High-Quality Concrete");
        add("block.mekanismelements.yellow_high_quality_concrete", "Yellow High-Quality Concrete");
        add("block.mekanismelements.aqua_high_quality_concrete_slab", "Aqua High-Quality Concrete Slab");
        add("block.mekanismelements.black_high_quality_concrete_slab", "Black High-Quality Concrete Slab");
        add("block.mekanismelements.blue_high_quality_concrete_slab", "Blue High-Quality Concrete Slab");
        add("block.mekanismelements.brown_high_quality_concrete_slab", "Brown High-Quality Concrete Slab");
        add("block.mekanismelements.cyan_high_quality_concrete_slab", "Cyan High-Quality Concrete Slab");
        add("block.mekanismelements.dark_red_high_quality_concrete_slab", "Dark Red High-Quality Concrete Slab");
        add("block.mekanismelements.gray_high_quality_concrete_slab", "Gray High-Quality Concrete Slab");
        add("block.mekanismelements.green_high_quality_concrete_slab", "Green High-Quality Concrete Slab");
        add("block.mekanismelements.high_quality_concrete_slab", "High-Quality Concrete Slab");
        add("block.mekanismelements.light_blue_high_quality_concrete_slab", "Light Blue High-Quality Concrete Slab");
        add("block.mekanismelements.light_gray_high_quality_concrete_slab", "Light Gray High-Quality Concrete Slab");
        add("block.mekanismelements.lime_high_quality_concrete_slab", "Lime High-Quality Concrete Slab");
        add("block.mekanismelements.magenta_high_quality_concrete_slab", "Magenta High-Quality Concrete Slab");
        add("block.mekanismelements.orange_high_quality_concrete_slab", "Orange High-Quality Concrete Slab");
        add("block.mekanismelements.pink_high_quality_concrete_slab", "Pink High-Quality Concrete Slab");
        add("block.mekanismelements.purple_high_quality_concrete_slab", "Purple High-Quality Concrete Slab");
        add("block.mekanismelements.red_high_quality_concrete_slab", "Red High-Quality Concrete Slab");
        add("block.mekanismelements.white_high_quality_concrete_slab", "White High-Quality Concrete Slab");
        add("block.mekanismelements.yellow_high_quality_concrete_slab", "Yellow High-Quality Concrete Slab");
        add("block.mekanismelements.aqua_high_quality_concrete_stairs", "Aqua High-Quality Concrete Stairs");
        add("block.mekanismelements.black_high_quality_concrete_stairs", "Black High-Quality Concrete Stairs");
        add("block.mekanismelements.blue_high_quality_concrete_stairs", "Blue High-Quality Concrete Stairs");
        add("block.mekanismelements.brown_high_quality_concrete_stairs", "Brown High-Quality Concrete Stairs");
        add("block.mekanismelements.cyan_high_quality_concrete_stairs", "Cyan High-Quality Concrete Stairs");
        add("block.mekanismelements.dark_red_high_quality_concrete_stairs", "Dark Red High-Quality Concrete Stairs");
        add("block.mekanismelements.gray_high_quality_concrete_stairs", "Gray High-Quality Concrete Stairs");
        add("block.mekanismelements.green_high_quality_concrete_stairs", "Green High-Quality Concrete Stairs");
        add("block.mekanismelements.high_quality_concrete_stairs", "High-Quality Concrete Stairs");
        add("block.mekanismelements.light_blue_high_quality_concrete_stairs", "Light Blue High-Quality Concrete Stairs");
        add("block.mekanismelements.light_gray_high_quality_concrete_stairs", "Light Gray High-Quality Concrete Stairs");
        add("block.mekanismelements.lime_high_quality_concrete_stairs", "Lime High-Quality Concrete Stairs");
        add("block.mekanismelements.magenta_high_quality_concrete_stairs", "Magenta High-Quality Concrete Stairs");
        add("block.mekanismelements.orange_high_quality_concrete_stairs", "Orange High-Quality Concrete Stairs");
        add("block.mekanismelements.pink_high_quality_concrete_stairs", "Pink High-Quality Concrete Stairs");
        add("block.mekanismelements.purple_high_quality_concrete_stairs", "Purple High-Quality Concrete Stairs");
        add("block.mekanismelements.red_high_quality_concrete_stairs", "Red High-Quality Concrete Stairs");
        add("block.mekanismelements.white_high_quality_concrete_stairs", "White High-Quality Concrete Stairs");
        add("block.mekanismelements.yellow_high_quality_concrete_stairs", "Yellow High-Quality Concrete Stairs");
        add("chemical.mekanismelements.americium", "Americium");
        add("chemical.mekanismelements.ammonia", "Ammonia");
        add("chemical.mekanismelements.ammonium_nitrate", "Ammonium Nitrate");
        add("chemical.mekanismelements.aqua_regia", "Aqua Regia");
        add("chemical.mekanismelements.beryllium", "Beryllium");
        add("chemical.mekanismelements.bromine", "Bromine");
        add("chemical.mekanismelements.californium", "Californium");
        add("chemical.mekanismelements.compressed_air", "Compressed Air");
        add("chemical.mekanismelements.concentrated_seawater", "Gaseous Concentrated Seawater");
        add("chemical.mekanismelements.curium", "Curium");
        add("chemical.mekanismelements.dissolved_spent_nuclear_waste", "Dissolved Spent Nuclear Waste");
        add("chemical.mekanismelements.helium", "Helium");
        add("chemical.mekanismelements.iodine", "Iodine");
        add("chemical.mekanismelements.lactose", "Lactose");
        add("chemical.mekanismelements.methanol", "Methanol");
        add("chemical.mekanismelements.methylamine", "Methylamine");
        add("chemical.mekanismelements.methylammonium_lead_iodide", "Methylammonium Lead Iodide");
        add("chemical.mekanismelements.netherite_acid", "Netherite Acid");
        add("chemical.mekanismelements.nitric_acid", "Nitric Acid");
        add("chemical.mekanismelements.nitric_oxide", "Nitric Oxide");
        add("chemical.mekanismelements.nitrogen", "Nitrogen");
        add("chemical.mekanismelements.nitrogen_dioxide", "Nitrogen Dioxide");
        add("chemical.mekanismelements.potassium_chloride", "Potassium Chloride");
        add("chemical.mekanismelements.potassium_hydroxide", "Potassium Hydroxide");
        add("chemical.mekanismelements.potassium_iodide", "Potassium Iodide");
        add("chemical.mekanismelements.seawater", "Gaseous Seawater");
        add("chemical.mekanismelements.strontium", "Strontium");
        add("chemical.mekanismelements.superheated_helium", "Superheated Helium");
        add("chemical.mekanismelements.xenon", "Xenon");
        add("chemical.mekanismelements.yttrium", "Yttrium");
        add("container.mekanismelements.adsorption_separator", "Adsorption Separator");
        add("container.mekanismelements.adsorption_type_seawater_metal_extractor", "Adsorption Type Seawater Metal Extractor");
        add("container.mekanismelements.air_compressor", "Air Compressor");
        add("container.mekanismelements.chemical_demolition_machine", "Chemical Demolition Machine");
        add("container.mekanismelements.organic_liquid_extractor", "Organic Liquid Extractor");
        add("container.mekanismelements.radiation_irradiator", "Radiation Irradiator");
        add("container.mekanismelements.seawater_pump", "Seawater Pump");
        add("description.mekanismelements.adsorption_separator", "This machine is capable of extracting only specific substances using adsorbents.");
        add("description.mekanismelements.air_compressor", "This machine can suck in ambient air and compress it into a gaseous state.");
        add("description.mekanismelements.chemical_demolition_machine", "A machine that uses chemicals to demolish materials.");
        add("description.mekanismelements.organic_liquid_extractor", "A machine to extract organic liquids from mobs.");
        add("description.mekanismelements.radiation_irradiator", "This machine can irradiate radiation efficiently.");
        add("description.mekanismelements.seawater_pump", "This pump can be used to extract seawater in the ocean biome.");
        add("effect.mekanismelements.good_sleep", "Good Sleep");
        add("effect.mekanismelements.radiation_resistance", "Radiation Resistance");
        add("effect.mekanismelements.sensory_paralysis", "Sensory Paralysis");
        add("item.mekanismelements.ammonia_bucket", "Liquid Ammonia Bucket");
        add("item.mekanismelements.ammonium_nitrate_bucket", "Liquid Ammonium Nitrate Bucket");
        add("item.mekanismelements.aqua_regia_bucket", "Liquid Aqua Regia Bucket");
        add("item.mekanismelements.beryllium_bucket", "Liquid Beryllium Bucket");
        add("item.mekanismelements.bromine_bucket", "Liquid Bromine Bucket");
        add("item.mekanismelements.compressed_air_bucket", "Liquid Compressed Air Bucket");
        add("item.mekanismelements.helium_bucket", "Liquid Helium Bucket");
        add("item.mekanismelements.iodine_bucket", "Liquid Iodine Bucket");
        add("item.mekanismelements.netherite_acid_bucket", "Liquid Netherite Acid Bucket");
        add("item.mekanismelements.nitric_acid_bucket", "Liquid Nitric Acid Bucket");
        add("item.mekanismelements.nitric_oxide_bucket", "Liquid Nitric Oxide Bucket");
        add("item.mekanismelements.nitrogen_bucket", "Liquid Nitrogen Bucket");
        add("item.mekanismelements.nitrogen_dioxide_bucket", "Liquid Nitrogen Dioxide Bucket");
        add("item.mekanismelements.potassium_chloride_bucket", "Liquid Potassium Chloride Bucket");
        add("item.mekanismelements.potassium_hydroxide_bucket", "Liquid Potassium Hydroxide Bucket");
        add("item.mekanismelements.potassium_iodide_bucket", "Liquid Potassium Iodide Bucket");
        add("item.mekanismelements.seawater_bucket", "Seawater Bucket");
        add("item.mekanismelements.strontium_bucket", "Liquid Strontium Bucket");
        add("item.mekanismelements.superheated_helium_bucket", "Liquid Superheated Helium Bucket");
        add("item.mekanismelements.xenon_bucket", "Liquid Xenon Bucket");
        add("item.mekanismelements.yttrium_bucket", "Liquid Yttrium Bucket");
        add("item.mekanismelements.dust_beryllium", "Beryllium Dust");
        add("item.mekanismelements.dust_calcium_oxide", "Calcium Oxide Dust");
        add("item.mekanismelements.dust_yttrium", "Yttrium Dust");
        add("item.mekanismelements.ingot_beryllium", "Beryllium Ingot");
        add("item.mekanismelements.ingot_refined_californium", "Refined Californium Ingot");
        add("item.mekanismelements.pellet_neutron_source", "Neutron Source Pellet");
        add("item.mekanismelements.high_performance_adsorbent", "High Performance Absorbent");
        add("item.mekanismelements.high_performance_adsorbent_beryllium", "Beryllium High Performance Absorbent");
        add("item.mekanismelements.high_performance_adsorbent_copper", "Copper High Performance Absorbent");
        add("item.mekanismelements.high_performance_adsorbent_gold", "Gold High Performance Absorbent");
        add("item.mekanismelements.high_performance_adsorbent_iron", "Iron High Performance Absorbent");
        add("item.mekanismelements.high_performance_adsorbent_lead", "Lead High Performance Absorbent");
        add("item.mekanismelements.high_performance_adsorbent_osmium", "Osmium High Performance Absorbent");
        add("item.mekanismelements.high_performance_adsorbent_tin", "Tin High Performance Absorbent");
        add("item.mekanismelements.high_performance_adsorbent_uranium", "Uranium High Performance Absorbent");
        add("item.mekanismelements.clump_high_quality_concrete_aqua", "Aqua High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_black", "Black High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_blue", "Blue High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_brown", "Brown High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_cyan", "Cyan High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_dark_red", "Dark Red High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete", "High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_gray", "Gray High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_green", "Green High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_light_blue", "Light Blue High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_light_gray", "Light Gray High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_lime", "Lime High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_magenta", "Magenta High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_orange", "Orange High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_pink", "Pink High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_purple", "Purple High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_red", "Red High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_white", "White High-Quality Concrete Clump");
        add("item.mekanismelements.clump_high_quality_concrete_yellow", "Yellow High-Quality Concrete Clump");
        add("item.mekanismelements.powder_high_quality_concrete_aqua", "Aqua High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_black", "Black High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_blue", "Blue High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_brown", "Brown High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_cyan", "Cyan High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_dark_red", "Dark Red High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete", "High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_gray", "Gray High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_green", "Green High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_light_blue", "Light Blue High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_light_gray", "Light Gray High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_lime", "Lime High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_magenta", "Magenta High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_orange", "Orange High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_pink", "Pink High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_purple", "Purple High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_red", "Red High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_white", "White High-Quality Concrete Powder");
        add("item.mekanismelements.powder_high_quality_concrete_yellow", "Yellow High-Quality Concrete Powder");
        add("item.mekanismelements.syringe_anesthetic", "Anesthetic Syringe");
        add("item.mekanismelements.syringe", "Syringe");
        add("item.mekanismelements.syringe_flame_retardant", "Flame Retardant Syringe");
        add("item.mekanismelements.syringe_levitation", "Levitation Syringe");
        add("item.mekanismelements.tablet_iodine", "Iodine Tablet");
        add("item.mekanismelements.tablet_poison", "Poison Tablet");
        add("item.mekanismelements.tablet_sleep_inducing", "Sleep Inducing Tablet");
        add("item.mekanismelements.unstable_californium_mixture", "Unstable Californium Mixture");
        add("sound_event.mekanismelements.tile.machine.air_compressor", "Spin Air Compressor Blades");
    }

    public static class ESES extends LanguageProvider {
        public ESES(PackOutput packOutput) {
            super(packOutput, MekanismElements.MODID, "es_es");
        }

        public ESES(PackOutput packOutput, String locale) {
            super(packOutput, MekanismElements.MODID, locale);
        }

        @Override
        protected void addTranslations() {
        add("constants.mekanismelements.mod_name", "Mekanism: Elements");
        add("advancements.mekanismelements.californium.title", "El alcance de la ciencia");
        add("advancements.mekanismelements.californium.description", "Refina californio, el elemento con el número atómico más alto que tiene aplicaciones prácticas");
        add("advancements.mekanismelements.neutron_source.title", "¿Por qué pensaste que esto era seguro?");
        add("advancements.mekanismelements.neutron_source.description", "Haz un pellet de fuente de neutrones con americio y berilio, y sostenlo");
        add("advancements.mekanismelements.radiation_irradiator.title", "Mini-reactor");
        add("advancements.mekanismelements.radiation_irradiator.description", "Construye un irradiador de radiación");
        add("advancements.mekanismelements.seawater_pump.title", "Mar-avilloso lo que hiciste allí");
        add("advancements.mekanismelements.seawater_pump.description", "Construye una bomba de agua de mar");
        add("block.mekanismelements.adsorption_separator", "Separador de adsorción");
        add("block.mekanismelements.air_compressor", "Compresor de aire");
        add("block.mekanismelements.chemical_demolition_machine", "Máquina de demolición química");
        add("block.mekanismelements.organic_liquid_extractor", "Extractor de líquidos orgánicos");
        add("block.mekanismelements.radiation_irradiator", "Irradiador de radiación");
        add("block.mekanismelements.radiation_shielding_concrete", "Hormigón de protección contra radiación");
        add("block.mekanismelements.seawater_pump", "Bomba de agua de mar");
        add("block.mekanismelements.ammonia", "Amoníaco líquido");
        add("block.mekanismelements.ammonium_nitrate", "Nitrato de amonio líquido");
        add("block.mekanismelements.aqua_regia", "Agua regia líquida");
        add("block.mekanismelements.beryllium", "Berilio líquido");
        add("block.mekanismelements.bromine", "Bromo líquido");
        add("block.mekanismelements.compressed_air", "Aire comprimido líquido");
        add("block.mekanismelements.helium", "Helio líquido");
        add("block.mekanismelements.iodine", "Yodo líquido");
        add("block.mekanismelements.netherite_acid", "Ácido de netherita líquida");
        add("block.mekanismelements.nitric_acid", "Ácido nítrico líquido");
        add("block.mekanismelements.nitric_oxide", "Óxido nítrico líquido");
        add("block.mekanismelements.nitrogen", "Nitrógeno líquido");
        add("block.mekanismelements.nitrogen_dioxide", "Dióxido de nitrógeno líquido");
        add("block.mekanismelements.potassium_chloride", "Cloruro de potasio líquido");
        add("block.mekanismelements.potassium_hydroxide", "Hidróxido de potasio líquido");
        add("block.mekanismelements.potassium_iodide", "Yoduro de potasio líquido");
        add("block.mekanismelements.seawater", "Agua de mar");
        add("block.mekanismelements.strontium", "Estroncio líquido");
        add("block.mekanismelements.superheated_helium", "Helio líquido sobrecalentado");
        add("block.mekanismelements.xenon", "Xenón líquido");
        add("block.mekanismelements.yttrium", "Itrio líquido");
        add("block.mekanismelements.aqua_high_quality_concrete", "Hormigón celeste de alta calidad");
        add("block.mekanismelements.black_high_quality_concrete", "Hormigón negro de alta calidad");
        add("block.mekanismelements.blue_high_quality_concrete", "Hormigón azul de alta calidad");
        add("block.mekanismelements.brown_high_quality_concrete", "Hormigón marrón de alta calidad");
        add("block.mekanismelements.cyan_high_quality_concrete", "Hormigón cian de alta calidad");
        add("block.mekanismelements.dark_red_high_quality_concrete", "Hormigón rojo oscuro de alta calidad");
        add("block.mekanismelements.gray_high_quality_concrete", "Hormigón gris de alta calidad");
        add("block.mekanismelements.green_high_quality_concrete", "Hormigón verde de alta calidad");
        add("block.mekanismelements.high_quality_concrete", "Hormigón de alta calidad");
        add("block.mekanismelements.light_blue_high_quality_concrete", "Hormigón azul claro de alta calidad");
        add("block.mekanismelements.light_gray_high_quality_concrete", "Hormigón gris claro de alta calidad");
        add("block.mekanismelements.lime_high_quality_concrete", "Hormigón verde lima de alta calidad");
        add("block.mekanismelements.magenta_high_quality_concrete", "Hormigón magenta de alta calidad");
        add("block.mekanismelements.orange_high_quality_concrete", "Hormigón naranja de alta calidad");
        add("block.mekanismelements.pink_high_quality_concrete", "Hormigón rosa de alta calidad");
        add("block.mekanismelements.purple_high_quality_concrete", "Hormigón morado de alta calidad");
        add("block.mekanismelements.red_high_quality_concrete", "Hormigón rojo de alta calidad");
        add("block.mekanismelements.white_high_quality_concrete", "Hormigón blanco de alta calidad");
        add("block.mekanismelements.yellow_high_quality_concrete", "Hormigón amarillo de alta calidad");
        add("block.mekanismelements.aqua_high_quality_concrete_slab", "Losa de hormigón celeste de alta calidad");
        add("block.mekanismelements.black_high_quality_concrete_slab", "Losa de hormigón negro de alta calidad");
        add("block.mekanismelements.blue_high_quality_concrete_slab", "Losa de hormigón azul de alta calidad");
        add("block.mekanismelements.brown_high_quality_concrete_slab", "Losa de hormigón marrón de alta calidad");
        add("block.mekanismelements.cyan_high_quality_concrete_slab", "Losa de hormigón cian de alta calidad");
        add("block.mekanismelements.dark_red_high_quality_concrete_slab", "Losa de hormigón rojo oscuro de alta calidad");
        add("block.mekanismelements.gray_high_quality_concrete_slab", "Losa de hormigón gris de alta calidad");
        add("block.mekanismelements.green_high_quality_concrete_slab", "Losa de hormigón verde de alta calidad");
        add("block.mekanismelements.high_quality_concrete_slab", "Losa de hormigón de alta calidad");
        add("block.mekanismelements.light_blue_high_quality_concrete_slab", "Losa de hormigón azul claro de alta calidad");
        add("block.mekanismelements.light_gray_high_quality_concrete_slab", "Losa de hormigón gris claro de alta calidad");
        add("block.mekanismelements.lime_high_quality_concrete_slab", "Losa de hormigón verde lima de alta calidad");
        add("block.mekanismelements.magenta_high_quality_concrete_slab", "Losa de hormigón magenta de alta calidad");
        add("block.mekanismelements.orange_high_quality_concrete_slab", "Losa de hormigón naranja de alta calidad");
        add("block.mekanismelements.pink_high_quality_concrete_slab", "Losa de hormigón rosa de alta calidad");
        add("block.mekanismelements.purple_high_quality_concrete_slab", "Losa de hormigón morado de alta calidad");
        add("block.mekanismelements.red_high_quality_concrete_slab", "Losa de hormigón rojo de alta calidad");
        add("block.mekanismelements.white_high_quality_concrete_slab", "Losa de hormigón blanco de alta calidad");
        add("block.mekanismelements.yellow_high_quality_concrete_slab", "Losa de hormigón amarillo de alta calidad");
        add("block.mekanismelements.aqua_high_quality_concrete_stairs", "Escaleras de hormigón celeste de alta calidad");
        add("block.mekanismelements.black_high_quality_concrete_stairs", "Escaleras de hormigón negro de alta calidad");
        add("block.mekanismelements.blue_high_quality_concrete_stairs", "Escaleras de hormigón azul de alta calidad");
        add("block.mekanismelements.brown_high_quality_concrete_stairs", "Escaleras de hormigón marrón de alta calidad");
        add("block.mekanismelements.cyan_high_quality_concrete_stairs", "Escaleras de hormigón cian de alta calidad");
        add("block.mekanismelements.dark_red_high_quality_concrete_stairs", "Escaleras de hormigón rojo oscuro de alta calidad");
        add("block.mekanismelements.gray_high_quality_concrete_stairs", "Escaleras de hormigón gris de alta calidad");
        add("block.mekanismelements.green_high_quality_concrete_stairs", "Escaleras de hormigón verde de alta calidad");
        add("block.mekanismelements.high_quality_concrete_stairs", "Escaleras de hormigón de alta calidad");
        add("block.mekanismelements.light_blue_high_quality_concrete_stairs", "Escaleras de hormigón azul claro de alta calidad");
        add("block.mekanismelements.light_gray_high_quality_concrete_stairs", "Escaleras de hormigón gris claro de alta calidad");
        add("block.mekanismelements.lime_high_quality_concrete_stairs", "Escaleras de hormigón verde lima de alta calidad");
        add("block.mekanismelements.magenta_high_quality_concrete_stairs", "Escaleras de hormigón magenta de alta calidad");
        add("block.mekanismelements.orange_high_quality_concrete_stairs", "Escaleras de hormigón naranja de alta calidad");
        add("block.mekanismelements.pink_high_quality_concrete_stairs", "Escaleras de hormigón rosa de alta calidad");
        add("block.mekanismelements.purple_high_quality_concrete_stairs", "Escaleras de hormigón morado de alta calidad");
        add("block.mekanismelements.red_high_quality_concrete_stairs", "Escaleras de hormigón rojo de alta calidad");
        add("block.mekanismelements.white_high_quality_concrete_stairs", "Escaleras de hormigón blanco de alta calidad");
        add("block.mekanismelements.yellow_high_quality_concrete_stairs", "Escaleras de hormigón amarillo de alta calidad");
        add("chemical.mekanismelements.americium", "Americio");
        add("chemical.mekanismelements.ammonia", "Amoníaco");
        add("chemical.mekanismelements.ammonium_nitrate", "Nitrato de amonio");
        add("chemical.mekanismelements.aqua_regia", "Agua regia");
        add("chemical.mekanismelements.beryllium", "Berilio");
        add("chemical.mekanismelements.bromine", "Bromo");
        add("chemical.mekanismelements.californium", "Californio");
        add("chemical.mekanismelements.compressed_air", "Aire comprimido");
        add("chemical.mekanismelements.concentrated_seawater", "Agua de mar concentrada gaseosa");
        add("chemical.mekanismelements.curium", "Curio");
        add("chemical.mekanismelements.dissolved_spent_nuclear_waste", "Desechos nucleares gastados disueltos");
        add("chemical.mekanismelements.helium", "Helio");
        add("chemical.mekanismelements.iodine", "Yodo");
        add("chemical.mekanismelements.lactose", "Lactosa");
        add("chemical.mekanismelements.methanol", "Metanol");
        add("chemical.mekanismelements.methylamine", "Metilamina");
        add("chemical.mekanismelements.methylammonium_lead_iodide", "Yoduro de plomo de metilamonio");
        add("chemical.mekanismelements.netherite_acid", "Ácido de netherita");
        add("chemical.mekanismelements.nitric_acid", "Ácido nítrico");
        add("chemical.mekanismelements.nitric_oxide", "Óxido nítrico");
        add("chemical.mekanismelements.nitrogen", "Nitrógeno");
        add("chemical.mekanismelements.nitrogen_dioxide", "Dióxido de nitrógeno");
        add("chemical.mekanismelements.potassium_chloride", "Cloruro de potasio");
        add("chemical.mekanismelements.potassium_hydroxide", "Hidróxido de potasio");
        add("chemical.mekanismelements.potassium_iodide", "Yoduro de potasio");
        add("chemical.mekanismelements.seawater", "Agua de mar gaseosa");
        add("chemical.mekanismelements.strontium", "Estroncio");
        add("chemical.mekanismelements.superheated_helium", "Helio sobrecalentado");
        add("chemical.mekanismelements.xenon", "Xenón");
        add("chemical.mekanismelements.yttrium", "Itrio");
        add("container.mekanismelements.adsorption_separator", "Separador de adsorción");
        add("container.mekanismelements.adsorption_type_seawater_metal_extractor", "Extractor de metales de agua de mar tipo adsorción");
        add("container.mekanismelements.air_compressor", "Compresor de aire");
        add("container.mekanismelements.chemical_demolition_machine", "Máquina de demolición química");
        add("container.mekanismelements.organic_liquid_extractor", "Extractor de líquidos orgánicos");
        add("container.mekanismelements.radiation_irradiator", "Irradiador de radiación");
        add("container.mekanismelements.seawater_pump", "Bomba de agua de mar");
        add("description.mekanismelements.adsorption_separator", "Esta máquina es capaz de extraer solo sustancias específicas utilizando adsorbentes.");
        add("description.mekanismelements.air_compressor", "Esta máquina puede succionar el aire ambiental y comprimirlo en estado gaseoso.");
        add("description.mekanismelements.chemical_demolition_machine", "Una máquina que utiliza productos químicos para demoler materiales.");
        add("description.mekanismelements.organic_liquid_extractor", "Una máquina para extraer líquidos orgánicos de mobs.");
        add("description.mekanismelements.radiation_irradiator", "Esta máquina puede irradiar radiación de manera eficiente.");
        add("description.mekanismelements.seawater_pump", "Esta bomba se puede usar para extraer agua de mar en el bioma de océano.");
        add("effect.mekanismelements.good_sleep", "Buen sueño");
        add("effect.mekanismelements.radiation_resistance", "Resistencia a la radiación");
        add("effect.mekanismelements.sensory_paralysis", "Parálisis sensorial");
        add("item.mekanismelements.ammonia_bucket", "Cubo de amoníaco líquido");
        add("item.mekanismelements.ammonium_nitrate_bucket", "Cubo de nitrato de amonio líquido");
        add("item.mekanismelements.aqua_regia_bucket", "Cubo de agua regia líquida");
        add("item.mekanismelements.beryllium_bucket", "Cubo de berilio líquido");
        add("item.mekanismelements.bromine_bucket", "Cubo de bromo líquido");
        add("item.mekanismelements.compressed_air_bucket", "Cubo de aire comprimido líquido");
        add("item.mekanismelements.helium_bucket", "Cubo de helio líquido");
        add("item.mekanismelements.iodine_bucket", "Cubo de yodo líquido");
        add("item.mekanismelements.netherite_acid_bucket", "Cubo de ácido de netherita líquida");
        add("item.mekanismelements.nitric_acid_bucket", "Cubo de ácido nítrico líquido");
        add("item.mekanismelements.nitric_oxide_bucket", "Cubo de óxido nítrico líquido");
        add("item.mekanismelements.nitrogen_bucket", "Cubo de nitrógeno líquido");
        add("item.mekanismelements.nitrogen_dioxide_bucket", "Cubo de dióxido de nitrógeno líquido");
        add("item.mekanismelements.potassium_chloride_bucket", "Cubo de cloruro de potasio líquido");
        add("item.mekanismelements.potassium_hydroxide_bucket", "Cubo de hidróxido de potasio líquido");
        add("item.mekanismelements.potassium_iodide_bucket", "Cubo de yoduro de potasio líquido");
        add("item.mekanismelements.seawater_bucket", "Cubo de agua de mar");
        add("item.mekanismelements.strontium_bucket", "Cubo de estroncio líquido");
        add("item.mekanismelements.superheated_helium_bucket", "Cubo de helio líquido sobrecalentado");
        add("item.mekanismelements.xenon_bucket", "Cubo de xenón líquido");
        add("item.mekanismelements.yttrium_bucket", "Cubo de itrio líquido");
        add("item.mekanismelements.dust_beryllium", "Polvo de berilio");
        add("item.mekanismelements.dust_calcium_oxide", "Polvo de óxido de calcio");
        add("item.mekanismelements.dust_yttrium", "Polvo de itrio");
        add("item.mekanismelements.ingot_beryllium", "Lingote de berilio");
        add("item.mekanismelements.ingot_refined_californium", "Lingote de californio refinado");
        add("item.mekanismelements.pellet_neutron_source", "Pellet de fuente de neutrones");
        add("item.mekanismelements.high_performance_adsorbent", "Absorbente de alto rendimiento");
        add("item.mekanismelements.high_performance_adsorbent_beryllium", "Absorbente de alto rendimiento de berilio");
        add("item.mekanismelements.high_performance_adsorbent_copper", "Absorbente de alto rendimiento de cobre");
        add("item.mekanismelements.high_performance_adsorbent_gold", "Absorbente de alto rendimiento de oro");
        add("item.mekanismelements.high_performance_adsorbent_iron", "Absorbente de alto rendimiento de hierro");
        add("item.mekanismelements.high_performance_adsorbent_lead", "Absorbente de alto rendimiento de plomo");
        add("item.mekanismelements.high_performance_adsorbent_osmium", "Absorbente de alto rendimiento de osmio");
        add("item.mekanismelements.high_performance_adsorbent_tin", "Absorbente de alto rendimiento de estaño");
        add("item.mekanismelements.high_performance_adsorbent_uranium", "Absorbente de alto rendimiento de uranio");
        add("item.mekanismelements.clump_high_quality_concrete_aqua", "Concentrado de hormigón celeste de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_black", "Concentrado de hormigón negro de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_blue", "Concentrado de hormigón azul de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_brown", "Concentrado de hormigón marrón de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_cyan", "Concentrado de hormigón cian de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_dark_red", "Concentrado de hormigón rojo oscuro de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete", "Concentrado de hormigón de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_gray", "Concentrado de hormigón gris de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_green", "Concentrado de hormigón verde de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_light_blue", "Concentrado de hormigón azul claro de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_light_gray", "Concentrado de hormigón gris claro de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_lime", "Concentrado de hormigón verde lima de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_magenta", "Concentrado de hormigón magenta de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_orange", "Concentrado de hormigón naranja de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_pink", "Concentrado de hormigón rosa de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_purple", "Concentrado de hormigón morado de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_red", "Concentrado de hormigón rojo de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_white", "Concentrado de hormigón blanco de alta calidad");
        add("item.mekanismelements.clump_high_quality_concrete_yellow", "Concentrado de hormigón amarillo de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_aqua", "Polvo de hormigón celeste de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_black", "Polvo de hormigón negro de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_blue", "Polvo de hormigón azul de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_brown", "Polvo de hormigón marrón de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_cyan", "Polvo de hormigón cian de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_dark_red", "Polvo de hormigón rojo oscuro de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete", "Polvo de hormigón de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_gray", "Polvo de hormigón gris de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_green", "Polvo de hormigón verde de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_light_blue", "Polvo de hormigón azul claro de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_light_gray", "Polvo de hormigón gris claro de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_lime", "Polvo de hormigón verde lima de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_magenta", "Polvo de hormigón magenta de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_orange", "Polvo de hormigón naranja de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_pink", "Polvo de hormigón rosa de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_purple", "Polvo de hormigón morado de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_red", "Polvo de hormigón rojo de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_white", "Polvo de hormigón blanco de alta calidad");
        add("item.mekanismelements.powder_high_quality_concrete_yellow", "Polvo de hormigón amarillo de alta calidad");
        add("item.mekanismelements.syringe_anesthetic", "Jeringa anestésica");
        add("item.mekanismelements.syringe", "Jeringa");
        add("item.mekanismelements.syringe_flame_retardant", "Jeringa ignífuga");
        add("item.mekanismelements.syringe_levitation", "Jeringa de levitación");
        add("item.mekanismelements.tablet_iodine", "Tableta de yodo");
        add("item.mekanismelements.tablet_poison", "Tableta de veneno");
        add("item.mekanismelements.tablet_sleep_inducing", "Tableta inductora de sueño");
        add("item.mekanismelements.unstable_californium_mixture", "Mezcla de californio inestable");
        add("sound_event.mekanismelements.tile.machine.air_compressor", "Aspas del compresor de aire girando");
        }
    }

    public static class JAJP extends LanguageProvider {
        public JAJP(PackOutput packOutput) {
            super(packOutput, MekanismElements.MODID, "ja_jp");
        }

        @Override
        protected void addTranslations() {
        add("advancements.mekanismelements.californium.description", "実用的な用途がある最も原子番号の大きい元素であるカリホルニウムを精製する");
        add("advancements.mekanismelements.californium.title", "科学の到達点");
        add("advancements.mekanismelements.radiation_irradiator.description", "放射線照射機をつくり、中性子反応の効率化を目指す");
        add("advancements.mekanismelements.radiation_irradiator.title", "ミニ原子炉");
        add("advancements.mekanismelements.neutron_source.description", "アメリシウムとベリリウムから中性子源ペレットを作り、持つ");
        add("advancements.mekanismelements.neutron_source.title", "なぜ安全だと思った？");
        add("advancements.mekanismelements.seawater_pump.description", "海水汲上ポンプをクラフトする");
        add("advancements.mekanismelements.seawater_pump.title", "海の恵み");
        add("block.mekanismelements.adsorption_separator", "吸着分離機");
        add("block.mekanismelements.air_compressor", "空気圧縮機");
        add("block.mekanismelements.ammonia", "液体アンモニア");
        add("block.mekanismelements.ammonium_nitrate", "液体硝酸アンモニウム");
        add("block.mekanismelements.aqua_high_quality_concrete", "水色の高品質コンクリート");
        add("block.mekanismelements.aqua_high_quality_concrete_slab", "水色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.aqua_high_quality_concrete_stairs", "水色の高品質コンクリートの階段");
        add("block.mekanismelements.aqua_regia", "液体王水");
        add("block.mekanismelements.beryllium", "液体ベリリウム");
        add("block.mekanismelements.black_high_quality_concrete", "黒色の高品質コンクリート");
        add("block.mekanismelements.black_high_quality_concrete_slab", "黒色の高品質コンクリート의 하프 블록");
        add("block.mekanismelements.black_high_quality_concrete_stairs", "黒色の高品質コンクリートの階段");
        add("block.mekanismelements.blue_high_quality_concrete", "青色の高品質コンクリート");
        add("block.mekanismelements.blue_high_quality_concrete_slab", "青色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.blue_high_quality_concrete_stairs", "青色の高品質コンクリートの階段");
        add("block.mekanismelements.bromine", "液体臭素");
        add("block.mekanismelements.brown_high_quality_concrete", "茶色の高品質コンクリート");
        add("block.mekanismelements.brown_high_quality_concrete_slab", "茶色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.brown_high_quality_concrete_stairs", "茶色の高品質コンクリートの階段");
        add("block.mekanismelements.chemical_demolition_machine", "化学解体機");
        add("block.mekanismelements.compressed_air", "液体圧縮空気");
        add("block.mekanismelements.cyan_high_quality_concrete", "青緑色の高品質コンクリート");
        add("block.mekanismelements.cyan_high_quality_concrete_slab", "青緑色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.cyan_high_quality_concrete_stairs", "青緑色の高品質コンクリートの階段");
        add("block.mekanismelements.dark_red_high_quality_concrete", "紅色の高品質コンクリート");
        add("block.mekanismelements.dark_red_high_quality_concrete_slab", "紅色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.dark_red_high_quality_concrete_stairs", "紅色の高品質コンクリートの階段");
        add("block.mekanismelements.gray_high_quality_concrete", "灰色の高品質コンクリート");
        add("block.mekanismelements.gray_high_quality_concrete_slab", "灰色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.gray_high_quality_concrete_stairs", "灰色の高品質コンクリートの階段");
        add("block.mekanismelements.green_high_quality_concrete", "緑色の高品質コンクリート");
        add("block.mekanismelements.green_high_quality_concrete_slab", "緑色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.green_high_quality_concrete_stairs", "緑色の高品質コンクリートの階段");
        add("block.mekanismelements.helium", "液体ヘリウム");
        add("block.mekanismelements.high_quality_concrete", "高品質コンクリート");
        add("block.mekanismelements.high_quality_concrete_slab", "高品質コンクリートのハーフブロック");
        add("block.mekanismelements.high_quality_concrete_stairs", "高品質コンクリートの階段");
        add("block.mekanismelements.hydrogen_cyanide", "液体シアン化水素");
        add("block.mekanismelements.iodine", "液体ヨウ素");
        add("block.mekanismelements.light_blue_high_quality_concrete", "空色の高品質コンクリート");
        add("block.mekanismelements.light_blue_high_quality_concrete_slab", "空色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.light_blue_high_quality_concrete_stairs", "空色の高品質コンクリートの階段");
        add("block.mekanismelements.light_gray_high_quality_concrete", "薄灰色の高品質コンクリート");
        add("block.mekanismelements.light_gray_high_quality_concrete_slab", "薄灰色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.light_gray_high_quality_concrete_stairs", "薄灰色の高品質コンクリートの階段");
        add("block.mekanismelements.lime_high_quality_concrete", "黄緑色の高品質コンクリート");
        add("block.mekanismelements.lime_high_quality_concrete_slab", "黄緑色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.lime_high_quality_concrete_stairs", "黄緑色の高品質コンクリートの階段");
        add("block.mekanismelements.magenta_high_quality_concrete", "赤紫色の高品質コンクリート");
        add("block.mekanismelements.magenta_high_quality_concrete_slab", "赤紫色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.magenta_high_quality_concrete_stairs", "赤紫色の高品質コンクリートの階段");
        add("block.mekanismelements.methane", "液体メタン");
        add("block.mekanismelements.netherite_acid", "液体ネザライト酸");
        add("block.mekanismelements.nitric_acid", "液体硝酸");
        add("block.mekanismelements.nitric_oxide", "液体一酸化窒素");
        add("block.mekanismelements.nitrogen", "液体窒素");
        add("block.mekanismelements.nitrogen_dioxide", "液体二酸化窒素");
        add("block.mekanismelements.orange_high_quality_concrete", "橙色の高品質コンクリート");
        add("block.mekanismelements.orange_high_quality_concrete_slab", "橙色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.orange_high_quality_concrete_stairs", "橙色の高品質コンクリートの階段");
        add("block.mekanismelements.organic_liquid_extractor", "有機液体抽出機");
        add("block.mekanismelements.pink_high_quality_concrete", "桃色の高品質コンクリート");
        add("block.mekanismelements.pink_high_quality_concrete_slab", "桃色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.pink_high_quality_concrete_stairs", "桃色の高品質コンクリートの階段");
        add("block.mekanismelements.potassium_chloride", "液体塩化カリウム");
        add("block.mekanismelements.potassium_cyanide", "液体シアン化カリウム");
        add("block.mekanismelements.potassium_hydroxide", "液体水酸化カリウム");
        add("block.mekanismelements.potassium_iodide", "液体ヨウ化カリウム");
        add("block.mekanismelements.purple_high_quality_concrete", "紫色の高品質コンクリート");
        add("block.mekanismelements.purple_high_quality_concrete_slab", "紫色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.purple_high_quality_concrete_stairs", "紫色の高品質コンクリートの階段");
        add("block.mekanismelements.radiation_irradiator", "放射線照射機");
        add("block.mekanismelements.radiation_shielding_concrete", "放射線遮蔽コンクリート");
        add("block.mekanismelements.red_high_quality_concrete", "赤色の高品質コンクリート");
        add("block.mekanismelements.red_high_quality_concrete_slab", "赤色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.red_high_quality_concrete_stairs", "赤色の高品質コンクリートの階段");
        add("block.mekanismelements.seawater", "海水");
        add("block.mekanismelements.seawater_pump", "海水汲上ポンプ");
        add("block.mekanismelements.strontium", "液体ストロンチウム");
        add("block.mekanismelements.superheated_helium", "液体過熱したヘリウム");
        add("block.mekanismelements.white_high_quality_concrete", "白色の高品質コンクリート");
        add("block.mekanismelements.white_high_quality_concrete_slab", "白色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.white_high_quality_concrete_stairs", "白色の高品質コンクリートの階段");
        add("block.mekanismelements.xenon", "液体キセノン");
        add("block.mekanismelements.yellow_high_quality_concrete", "黄色の高品質コンクリート");
        add("block.mekanismelements.yellow_high_quality_concrete_slab", "黄色の高品質コンクリートのハーフブロック");
        add("block.mekanismelements.yellow_high_quality_concrete_stairs", "黄色の高品質コンクリートの階段");
        add("block.mekanismelements.yttrium", "液体イットリウム");
        add("constants.mekanismelements.mod_name", "Mekanism: Elements");
        add("container.mekanismelements.adsorption_separator", "吸着分離機");
        add("container.mekanismelements.air_compressor", "空気圧縮機");
        add("container.mekanismelements.chemical_demolition_machine", "化学解体機");
        add("container.mekanismelements.organic_liquid_extractor", "有機液体抽出機");
        add("container.mekanismelements.radiation_irradiator", "放射線照射機");
        add("container.mekanismelements.seawater_pump", "海水汲上ポンプ");
        add("description.mekanismelements.adsorption_separator", "吸着剤を用いて特定の物質だけを抽出することができます。");
        add("description.mekanismelements.air_compressor", "周囲の空気を吸い込み、圧縮してガス状にすることができます。");
        add("description.mekanismelements.organic_liquid_extractor", "モブから有機液体を取り出す機械です。");
        add("description.mekanismelements.radiation_irradiator", "粒子を加速させ、放射線を効率よく照射できる機械です。");
        add("description.mekanismelements.seawater_pump", "このポンプを使うことで海バイオームの水を海水として吸い上げることができます。");
        add("effect.mekanismelements.good_sleep", "快眠");
        add("effect.mekanismelements.radiation_resistance", "放射線耐性");
        add("effect.mekanismelements.sensory_paralysis", "感覚麻痺");
        add("chemical.mekanismelements.americium", "アメリシウム");
        add("chemical.mekanismelements.ammonia", "アンモニア");
        add("chemical.mekanismelements.ammonium_nitrate", "硝酸アンモニウム");
        add("chemical.mekanismelements.aqua_regia", "王水");
        add("chemical.mekanismelements.beryllium", "ベリリウム");
        add("chemical.mekanismelements.bromine", "臭素");
        add("chemical.mekanismelements.californium", "カリホルニウム");
        add("chemical.mekanismelements.compressed_air", "圧縮空気");
        add("chemical.mekanismelements.concentrated_seawater", "ガス状の濃縮海水");
        add("chemical.mekanismelements.curium", "キュリウム");
        add("chemical.mekanismelements.dissolved_spent_nuclear_waste", "溶解した使用済み核廃棄物");
        add("chemical.mekanismelements.helium", "ヘリウム");
        add("chemical.mekanismelements.hydrogen_cyanide", "シアン化水素");
        add("chemical.mekanismelements.iodine", "ヨウ素");
        add("chemical.mekanismelements.lactose", "乳糖");
        add("chemical.mekanismelements.methane", "メタン");
        add("chemical.mekanismelements.netherite_acid", "ネザライト酸");
        add("chemical.mekanismelements.nitric_acid", "硝酸");
        add("chemical.mekanismelements.nitric_oxide", "一酸化窒素");
        add("chemical.mekanismelements.nitrogen", "窒素");
        add("chemical.mekanismelements.nitrogen_dioxide", "二酸化窒素");
        add("chemical.mekanismelements.potassium_chloride", "塩化カリウム");
        add("chemical.mekanismelements.potassium_cyanide", "シアン化カリウム");
        add("chemical.mekanismelements.potassium_hydroxide", "水酸化カリウム");
        add("chemical.mekanismelements.potassium_iodide", "ヨウ化カリウム");
        add("chemical.mekanismelements.seawater", "ガス状の海水");
        add("chemical.mekanismelements.strontium", "ストロンチウム");
        add("chemical.mekanismelements.superheated_helium", "過熱したヘリウム");
        add("chemical.mekanismelements.xenon", "キセノン");
        add("chemical.mekanismelements.yttrium", "イットリウム");
        add("item.mekanismelements.ammonia_bucket", "液体アンモニア入りバケツ");
        add("item.mekanismelements.ammonium_nitrate_bucket", "液体硝酸アンモニウム入りバケツ");
        add("item.mekanismelements.aqua_regia_bucket", "液体王水入りバケツ");
        add("item.mekanismelements.beryllium_bucket", "液体ベリリウム入りバケツ");
        add("item.mekanismelements.dust_beryllium", "ベリリウムの粉");
        add("item.mekanismelements.ingot_beryllium", "ベリリウムインゴット");
        add("item.mekanismelements.bromine_bucket", "液体臭素入りバケツ");
        add("item.mekanismelements.clump_high_quality_concrete", "高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_aqua", "水色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_black", "黒色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_blue", "青色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_brown", "茶色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_cyan", "青緑色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_dark_red", "紅色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_gray", "灰色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_green", "緑色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_light_blue", "空色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_light_gray", "薄灰色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_lime", "黄緑色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_magenta", "赤紫色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_orange", "橙色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_pink", "桃色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_purple", "紫色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_red", "赤色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_white", "白色の高品質コンクリートの塊");
        add("item.mekanismelements.clump_high_quality_concrete_yellow", "黄色の高品質コンクリートの塊");
        add("item.mekanismelements.compressed_air_bucket", "液体圧縮空気入りバケツ");
        add("item.mekanismelements.dust_calcium_oxide", "酸化カルシウムの粉");
        add("item.mekanismelements.helium_bucket", "液体ヘリウム入りバケツ");
        add("item.mekanismelements.hydrogen_cyanide_bucket", "液体シアン化水素入りバケツ");
        add("item.mekanismelements.high_performance_adsorbent", "高性能吸着剤");
        add("item.mekanismelements.high_performance_adsorbent_beryllium", "ベリリウム用高性能吸着剤");
        add("item.mekanismelements.high_performance_adsorbent_copper", "銅用高性能吸着剤");
        add("item.mekanismelements.high_performance_adsorbent_gold", "金用高性能吸着剤");
        add("item.mekanismelements.high_performance_adsorbent_iron", "鉄用高性能吸着剤");
        add("item.mekanismelements.high_performance_adsorbent_lead", "鉛用高性能吸着剤");
        add("item.mekanismelements.high_performance_adsorbent_osmium", "オスミウム用高性能吸着剤");
        add("item.mekanismelements.high_performance_adsorbent_tin", "錫用高性能吸着剤");
        add("item.mekanismelements.high_performance_adsorbent_uranium", "ウラン用高性能吸着剤");
        add("item.mekanismelements.ingot_refined_californium", "精製カリホルニウムインゴット");
        add("item.mekanismelements.iodine_bucket", "液体ヨウ素入りバケツ");
        add("item.mekanismelements.methane_bucket", "液体メタン入りバケツ");
        add("item.mekanismelements.netherite_acid_bucket", "液体ネザライト酸入りバケツ");
        add("item.mekanismelements.nitric_acid_bucket", "液体硝酸入りバケツ");
        add("item.mekanismelements.nitric_oxide_bucket", "液体一酸化窒素入りバケツ");
        add("item.mekanismelements.nitrogen_bucket", "液体窒素入りバケツ");
        add("item.mekanismelements.nitrogen_dioxide_bucket", "液体二酸化窒素入りバケツ");
        add("item.mekanismelements.pellet_neutron_source", "中性子源ペレット");
        add("item.mekanismelements.potassium_chloride_bucket", "液体塩化カリウム入りバケツ");
        add("item.mekanismelements.potassium_cyanide_bucket", "液体シアン化カリウム入りバケツ");
        add("item.mekanismelements.potassium_hydroxide_bucket", "液体水酸化カリウム入りバケツ");
        add("item.mekanismelements.potassium_iodide_bucket", "液体ヨウ化カリウム入りバケツ");
        add("item.mekanismelements.powder_high_quality_concrete", "高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_aqua", "水色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_black", "黒色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_blue", "青色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_brown", "茶色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_cyan", "青緑色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_dark_red", "紅色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_gray", "灰色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_green", "緑色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_light_blue", "空色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_light_gray", "薄灰色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_lime", "黄緑色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_magenta", "赤紫色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_orange", "橙色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_pink", "桃色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_purple", "紫色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_red", "赤色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_white", "白色の高品質コンクリートの粉");
        add("item.mekanismelements.powder_high_quality_concrete_yellow", "黄色の高品質コンクリートの粉");
        add("item.mekanismelements.seawater_bucket", "海水入りバケツ");
        add("item.mekanismelements.strontium_bucket", "液体ストロンチウム入りバケツ");
        add("item.mekanismelements.superheated_helium_bucket", "液体過熱したヘリウム入りバケツ");
        add("item.mekanismelements.syringe", "注射器");
        add("item.mekanismelements.syringe_anesthetic", "全身麻酔薬入り注射器");
        add("item.mekanismelements.syringe_flame_retardant", "難燃剤入り注射器");
        add("item.mekanismelements.syringe_levitation", "浮遊剤入り注射器");
        add("item.mekanismelements.tablet_iodine", "ヨウ素剤");
        add("item.mekanismelements.tablet_poison", "毒素剤");
        add("item.mekanismelements.tablet_sleep_inducing", "睡眠導入剤");
        add("item.mekanismelements.unstable_californium_mixture", "不安定なカリホルニウム混合物");
        add("item.mekanismelements.xenon_bucket", "液体キセノン入りバケツ");
        add("item.mekanismelements.yttrium_bucket", "液体イットリウム入りバケツ");
        add("sound_event.mekanismelements.tile.machine.air_compressor", "空気圧縮機の羽が回転する");
        }
    }
}